apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sardeenz-app-data
  labels:
    app: sardeenz
    app.kubernetes.io/name: sardeenz
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Small - just for SQLite database and app data
