apiVersion: v1
kind: Service
metadata:
  name: sardeenz
  labels:
    app: sardeenz
    app.kubernetes.io/name: sardeenz
    app.kubernetes.io/component: ml-platform
    app.kubernetes.io/part-of: sardeenz
spec:
  type: ClusterIP
  selector:
    app: sardeenz
  ports:
    - name: backend
      port: 3000
      targetPort: backend
      protocol: TCP
  sessionAffinity: None
